language: "python"
python: "3.6"
install:
  - pip install requests pyyaml pytest-cov python-coveralls httpretty codacy-coverage
script:
  - python3 -m pytest --cov=.
after_success:
  - coveralls
  - coverage xml
  - python-codacy-coverage -r coverage.xml
notifications:
  - email: false
