language: "python"
python: "3.6"
install:
  - pip install requests pyyaml pytest-cov python-coveralls httpretty
script:
  - python3 -m pytest --cov=.
after_success:
  - coveralls
notifications:
  - email: false
